# Generated by Django 5.1.7 on 2026-03-04 00:07

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_profile_image_path, verbose_name='الصورة الشخصية')),
                ('scanned_links', models.IntegerField(default=0, verbose_name='الروابط الممسوحة')),
                ('detected_threats', models.IntegerField(default=0, verbose_name='التهديدات المكتشفة')),
                ('accuracy_rate', models.FloatField(default=0.0, verbose_name='نسبة الدقة')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='البريد الإلكتروني موثق')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('settings', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رمز إعادة تعيين كلمة المرور',
                'verbose_name_plural': 'رموز إعادة تعيين كلمة المرور',
            },
        ),
    ]
