# Generated by Django 5.1.7 on 2026-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailverification',
            name='last_request_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Password Reset')], default='register', max_length=20),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='request_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
