# Generated by Django 5.1.7 on 2026-03-04 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=2000, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=100, verbose_name='نوع التهديد')),
                ('severity', models.IntegerField(default=3, verbose_name='درجة الخطورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('source', models.CharField(default='system', max_length=100, verbose_name='المصدر')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'رابط محظور',
                'verbose_name_plural': 'الروابط المحظورة',
                'indexes': [models.Index(fields=['domain'], name='scans_black_domain_e701e1_idx'), models.Index(fields=['threat_type'], name='scans_black_threat__a8aa6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=2000, verbose_name='الرابط')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='النطاق')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('safe', models.BooleanField(null=True, verbose_name='آمن')),
                ('safety_status', models.CharField(choices=[('safe', 'آمن'), ('suspicious', 'مشبوه'), ('dangerous', 'خطير')], default='suspicious', max_length=20, verbose_name='حالة الأمان')),
                ('score', models.IntegerField(default=0, verbose_name='نسبة الأمان')),
                ('details', models.JSONField(default=list, verbose_name='تفاصيل الفحص')),
                ('threats_found', models.JSONField(default=list, verbose_name='التهديدات المكتشفة')),
                ('threats_count', models.IntegerField(default=0, verbose_name='عدد التهديدات')),
                ('response_time', models.FloatField(default=0, verbose_name='زمن الاستجابة')),
                ('server_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='معلومات السيرفر')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفحص')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتيجة فحص',
                'verbose_name_plural': 'نتائج الفحوصات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_queues', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.scanresult')),
            ],
            options={
                'verbose_name': 'قائمة انتظار الفحص',
                'verbose_name_plural': 'قوائم انتظار الفحوصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['-timestamp'], name='scans_scanr_timesta_fffec1_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['user', '-timestamp'], name='scans_scanr_user_id_8e5d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['safe'], name='scans_scanr_safe_d1ca7c_idx'),
        ),
    ]
