# Generated by Django 5.1.7 on 2026-03-07 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_remove_scanqueue_result_remove_scanqueue_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('last_result', models.CharField(blank=True, max_length=50, null=True)),
                ('threat_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'رابط',
                'verbose_name_plural': 'الروابط',
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('label', models.CharField(max_length=50)),
                ('source', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بيانات التدريب',
                'verbose_name_plural': 'بيانات التدريب',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('safe', models.BooleanField(null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('source', models.CharField(default='system', max_length=100)),
                ('details', models.JSONField(default=list)),
                ('threats_found', models.JSONField(default=list)),
                ('threats_count', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0)),
                ('server_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فحص',
                'verbose_name_plural': 'الفحوصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['url_hash'], name='scans_scan_url_has_4c97c0_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['domain'], name='scans_scan_domain_c26ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['created_at'], name='scans_scan_created_89347f_idx'),
        ),
    ]
