# Generated by Django 5.1.7 on 2026-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_link_trainingdataset_scan_delete_scanresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCache',
            fields=[
                ('url_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('result', models.CharField(max_length=50)),
                ('threat_level', models.CharField(default='none', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'كاش الروابط',
                'verbose_name_plural': 'كاش الروابط',
                'indexes': [models.Index(fields=['url_hash'], name='scans_urlca_url_has_6881dd_idx'), models.Index(fields=['expires_at'], name='scans_urlca_expires_e2e0e9_idx')],
            },
        ),
    ]
