# Generated by Django 5.1.7 on 2026-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_url_cache_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
