# Generated by Django 5.1.7 on 2026-03-13 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=2000, verbose_name='الرابط المشبوه')),
                ('category', models.CharField(max_length=100, verbose_name='نوع التهديد')),
                ('description', models.TextField(blank=True, verbose_name='وصف إضافي')),
                ('severity', models.IntegerField(choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'عالي'), (4, 'خطير'), (5, 'حرج')], default=3, verbose_name='درجة الخطورة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewing', 'قيد التحقيق'), ('confirmed', 'تم التأكيد'), ('rejected', 'مرفوض'), ('resolved', 'تم الحل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم التتبع')),
                ('reporter_name', models.CharField(max_length=255, verbose_name='اسم المبلغ')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للمبلغ')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='بلغ بشكل مجهول')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='ملاحظات التحقيق')),
                ('is_confirmed_threat', models.BooleanField(default=False, verbose_name='تهديد مؤكد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف من قبل المستخدم')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('is_internal', models.BooleanField(default=False, verbose_name='داخلي (للمشرفين فقط)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='reports_rep_created_f226dd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tracking_number'], name='reports_rep_trackin_da1d2e_idx'),
        ),
    ]
